version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=SecurePass123!
    volumes:
      - nifi-data:/opt/nifi/nifi-current/data
      - ./nifi/flows:/opt/nifi/nifi-current/flows
    networks:
      - nifi-network

networks:
  nifi-network:
    driver: bridge

volumes:
  nifi-data: